### ISSUE TITLE
Why can't import account by private key?

### ISSUE THREAD

**Issue by mttowhid** [suiet/suiet#162]
There is no option to import account by private key. All people haven't always mnemic phrase they collect private key and they always use private key to improve there account. So there have to a option to import a account by private key.

Sui address: 0x21c56e5097c29af3085b6abf241313d0f2e91792adc8422718e76ac004bcd152

**Comment by fredliang44** [comment]
For the optimal security and convenience of your wallet, it is highly recommended to use a mnemonic phrase for backup purposes rather than relying on a private key. A mnemonic phrase, which consists of a series of words, is not only easier to remember but also offers a higher level of security.

Furthermore, it is important to note that backing up only the private key would not allow you to recover any other accounts associated with your wallet. On the other hand, using a mnemonic phrase grants you access to multiple addresses within your wallet, ensuring better privacy and flexibility in managing your funds. So, to safeguard your assets and maximize your wallet's functionality, opt for a mnemonic phrase backup over a private key backup.

**Comment by jwcheon** [comment]
@fredliang44 So basically importing mnemonic phrase of Wallet #1 should import the rest of Wallets created on the same Suiet chrome extension right?

My Suiet was randomly reset despite having Passkey and all, trying to recover my wallets and I only do have mnemonic phrase of Wallet #1 only. Tried importing it on a separate PC and only got me my Wallet #1 but not the rest.. what should I try doing now?

**Comment by Sceat** [comment]
Still Suiet should support importing by privateKey correctly, it's not always wanted to use a mnemonic. The default export format of a Sui private key is base64, which is not supported by Suiet

**Comment by bruceeewong** [comment]
This feature is supported by the date of Oct 9, 2024.
