### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by Vans202226** [suiet/suiet#225]
Why I keep getting Invalid Parameter, I need to link my SUI wallet to taskon, but this error is getting on my way. 

PS: I link my 4 wallet on taskon and I didn't encounter any problem, but with SUI this error is keep pop-up up! 

SnapShot Link Below 

https://github.com/suiet/suiet/assets/139128474/ae34279f-ca71-414d-9249-82b323dd4f70

**Comment by bruceeewong** [comment]
Hi, sorry for the inconvenience caused by our product. Can you first verify your assets on other wallets such as the official [Sui Wallet - install link](https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil). Our wallet is having some display issues regarding the update of blockchain fullnode. We are working on it.
