### ISSUE TITLE
Please help me I can't unstack

### ISSUE THREAD

**Issue by Icuting** [suiet/suiet#227]
I have such a mistake, who knows what to do to get my coins back?
![image](https://github.com/suiet/suiet/assets/40005109/1104765b-e4f7-4a1f-aba3-b1c82998ebbf)

**Comment by asgharsata1** [comment]
hi

**Comment by bruceeewong** [comment]
Hi, sorry for the inconvenience caused by our product. Can you first verify your assets on other wallets such as the official [Sui Wallet - install link](https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil). Our wallet is having some display issues regarding the update of blockchain fullnode. We are working on it.
