### ISSUE TITLE
Error message preventing any actions or updates inside wallet

### ISSUE THREAD

**Issue by mcconnachiet** [suiet/suiet#228]
When opening wallet. Error displays multiple times continuously:

Fetch balance failed: Post "http://fullnode:9000": dial tcp: lookup fullnode on 127.0.0.11:53: server misbehaving

Unable to update or see tokens. Unable to swap or send tokens.
Tokens in wallet are SUI and SUIP.

Priority 1 defect.

**Comment by bruceeewong** [comment]
Hi, sorry for the inconvenience caused by our product. Can you first verify your assets on other wallets such as the official [Sui Wallet - install link](https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil). Our wallet is having some display issues regarding the update of blockchain fullnode. We are working on it.

**Comment by hakushu48** [comment]
Does this issue still happen?"
My Suiet has been working fine for months, but it suddenly doesn't work today with the same issue.

**Comment by hakushu48** [comment]
fixed. temporary issue.

**Comment by DenysRakhuba** [comment]
I keep encountering the same error when attempting to switch to the testnet. Is there a way to manually change the default node to avoid this issue from occurring again?

**Comment by bruceeewong** [comment]
> I keep encountering the same error when attempting to switch to the testnet. Is there a way to manually change the default node to avoid this issue from occurring again?

Hey, sorry for the inconvenience. We don't support custom node right now. But I would like to know what error did it show?
