### ISSUE TITLE
cant trade,claim my tokens

### ISSUE THREAD

**Issue by StefanMB13** [suiet/suiet#229]

**Comment by bruceeewong** [comment]
Hi, sorry for the inconvenience caused by our product. Can you first verify your assets on other wallets such as the official [Sui Wallet - install link](https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil). Our wallet is having some display issues regarding the update of blockchain fullnode. We are working on it.

**Comment by StefanMB13** [comment]
I solved the problem on Google Chrome level there was transaction with
error which was not finalized, Thank you
Stefan

**Comment by StefanMB13** [comment]
I'm using Suiet wallet

**Comment by StefanMB13** [comment]
Awesome, thanks for the update!
