### ISSUE TITLE
Haven´t received my tokens from CEX

### ISSUE THREAD

**Issue by Xalu02** [suiet/suiet#230]
Hi, I recently sent some SUI from my Bybit Account to my Suite Wallet and unfortunately didn´t receive them... I send it via SUI Chain and the wallet address is also correct. Can someone help?

**Comment by bruceeewong** [comment]
Hi, sorry for the inconvenience caused by our product. Can you first verify your assets on other wallets such as the official [Sui Wallet - install link](https://chromewebstore.google.com/detail/sui-wallet/opcgpfmipidbgpenhmajoajpbobppdil). Our wallet is having some display issues regarding the update of blockchain fullnode. We are working on it.
